version: "3.9"

services:
  mikroseclist:
    image: mikroseclist:latest
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: mikroseclist
    command: ["python", "-m", "mikroseclist.main"]
    environment:
      MIKROTIK_HOST: ${MIKROTIK_HOST:-'192.168.88.1'}
      MIKROTIK_USER: ${MIKROTIK_USER:-'admin'}
      MIKROTIK_PASSWORD: ${MIKROTIK_PASSWORD:-'password'}
      BLOCKLIST_URL: ${BLOCKLIST_URL}
      SYNC_INTERVAL_MIN: 15
    volumes:
      - ./:/srv/
    restart: on-failure
