version: "3.9"

services:
  microseclist:
    image: microseclist:latest
    container_name: microseclist
    command: ["python", "-m", "microseclist.main"]
    environment:
      MIKROTIK_HOST: ${MIKROTIK_HOST:-'192.168.88.1'}
      MIKROTIK_USER: ${MIKROTIK_USER:-'admin'}
      MIKROTIK_PASSWORD: ${MIKROTIK_PASSWORD:-'password'}
      BLOCKLIST_URL: 'http://blocklist:41412/security/blocklist?ipv4only'
      SYNC_INTERVAL_MIN: 15
    restart: on-failure
